/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Trigger_out.h"
#include "Clock.h"
#include "echo_aliases.h"
#include "echo.h"
#include "CLK_aliases.h"
#include "CLK.h"
#include "Timer.h"
#include "Trigger_aliases.h"
#include "Trigger.h"
#include "DT_aliases.h"
#include "DT.h"
#include "QuadDec.h"
#include "Clock_1.h"
#include "C1_left_aliases.h"
#include "C1_left.h"
#include "A1_left_aliases.h"
#include "A1_left.h"
#include "D1_right_aliases.h"
#include "D1_right.h"
#include "B1_right_aliases.h"
#include "B1_right.h"
#include "A2_left_aliases.h"
#include "A2_left.h"
#include "C2_left_aliases.h"
#include "C2_left.h"
#include "B2_right_aliases.h"
#include "B2_right.h"
#include "D2_right_aliases.h"
#include "D2_right.h"
#include "PWM.h"
#include "Clock_2.h"
#include "PWM_1.h"
#include "Clock_3.h"
#include "PWM_2.h"
#include "Clock_4.h"
#include "Clock_5.h"
#include "PWM_3.h"
#include "UART.h"
#include "QuadDec_Cnt8.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

